name: MS Teams Deploy Card

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amolmt/microsoft-teams-pull-request-notifications@v1
        with:
          teams_webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
