name: Build Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc python3-pip
          pip install requests  # If needed for other purposes

      - name: Run tests
        id: run_tests
        run: |
          chmod +x ifcc-test_PR.py
          python3 ifcc-test_PR.py testfiles/ || echo "Tests failed" > test_failure.log

      - name: Annotate PR on failure
        if: failure()
        run: |
          echo "::error::Building tests failed! Check the logs for details."

      - name: Comment on PR if tests fail
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚨 **Some tests have failed!**
            Please check the logs for details.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
